XSOAR (Independent Publisher)
microsoft/PowerPlatformConnectors pull request #1546
Opened 2022-03-31 18:23 UTC by landonc

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

Please note that we are experiencing a significant delay due to COVID delays, unanticipated team leaves, and high volume of connector submissions. 

- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [X] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [X] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [X] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md. 

![connection_test_success](https://user-images.githubusercontent.com/742900/161123885-cac55a9e-fd48-4e06-8ea6-4cbde8748b00.png)
![flow_success](https://user-images.githubusercontent.com/742900/161123891-f96a9b73-0d66-4d3c-9a96-efbd26f63107.png)

2022-04-14 22:43 UTC, sriyen-msft requested changes

2022-04-14 22:43 UTC, sriyen-msft commented on independent-publisher-connectors/XSOAR/.gitignore
> +settings.json
@landonc Please remove this file

2022-04-14 22:43 UTC, sriyen-msft commented on independent-publisher-connectors/XSOAR/Readme.md
> +API keys are created by configuring an integration instance within XSOAR.
@landonc Can you please provide more details in step-by-step format to obtain an API key from XSOAR

2022-04-14 22:43 UTC, sriyen-msft commented on independent-publisher-connectors/XSOAR/apiDefinition.swagger.json
> +      "propertyValue": "https://www.paloaltonetworks.com/"
@landonc Please provide specific website URL of the connector service like below:
https://start.paloaltonetworks.com/sign-up-for-community-edition.html

2022-04-14 22:43 UTC, sriyen-msft commented on independent-publisher-connectors/XSOAR/apiDefinition.swagger.json
> +            "description": "API key is missing or invalid",
@landonc No response schema is not allowed anymore, which means no dynamic content will be shown in the output and makers have to use parse JSON to parse the response. Please provide a valid response schema definition for all the operations in the swagger. **This applies to all the empty schemas in the swagger.**

2022-04-14 22:43 UTC, sriyen-msft commented on independent-publisher-connectors/XSOAR/apiProperties.json
> +    "publisher": "Landon Chelf"
@landonc Please add stackOwner property as well.

2022-04-26 23:16 UTC, samrat-gavale approved these changes

2022-05-05 00:35 UTC, sriyen-msft commented
[[certify-connector]]

2022-05-06 00:07 UTC, sriyen-msft requested changes

2022-05-06 00:07 UTC, sriyen-msft commented on independent-publisher-connectors/XSOAR/apiDefinition.swagger.json
> +      "email": "landon.chelf@fisglobal.com"
@landonc Syntax error: Can you please add a comma after email value ?

2022-05-10 20:39 UTC, sriyen-msft commented on independent-publisher-connectors/XSOAR/apiDefinition.swagger.json
> +      "email": "landon.chelf@fisglobal.com"
@landonc Please raise a PR to fix it, thanks in advance.

2022-05-10 20:39 UTC, sriyen-msft commented
@landonc Congratulations! The deployment of your connector and documentation page is now complete, We have a short [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR0BHMrjhL0hDmckROosW6AFURERIVUUzMk5XRzJGV1dJM1Q5RVZJUjFXSC4u) on the connector certification process that we would like for you to complete. Your feedback is appreciated and will help us improve the program, Thanks.

2022-05-10 20:39 UTC, sriyen-msft approved these changes

2022-05-10 20:39 UTC, merged