USB4SAP : initial pull 10/14/22
microsoft/PowerPlatformConnectors pull request #2059
Opened 2022-10-14 17:41 UTC by ecsadm

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [X] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [X] I attest that the connector works and I verified by deploying and testing all the operations. 
- [X] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [X] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [X] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [X] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2022-10-14 19:14 UTC, Amjed-Ayoub requested changes

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/Readme.md
> +Large datasets extraction may result in time outs as configured in the REST API systems
@ecsadm all files should be free of grammatical errors and typos. May I ask you please to change "time outs" to "timeouts".

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +                "description": "The GET call extracts data alongwith its metadata from SAP, based on the selection criteria by user or background scheduled job",
@ecsadm all Operations descriptions should end with a period. No period required only if there's a single word.
Please see this useful [documentation](https://learn.microsoft.com/en-us/connectors/custom-connectors/connector-string-guidance#operations)
all files should be free of grammatical errors and typos. May I ask you please to change "alongwith" to "along with".

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +                "summary": "GET call to extract metadata & data from SAP data objects",
@ecsadm special characters in not allowed in the operation summary. pleases remove the "&".

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +                        "x-example": "ObjectName eq 'T001W' and ObjectType eq 'T' and Delimiter eq '|' and ImportGeneric eq 'ALVV-MG' and DataDest eq '0:0|' "
@ecsadm all parameters should have 
"x-ms-summary": "Your Summary"
"description": "Your description"
Please see our docs [here](https://learn.microsoft.com/en-us/connectors/custom-connectors/connector-string-guidance#parameters)

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +                        "x-example": "json"
@ecsadm all parameters should have 
"x-ms-summary": "Your Summary"
"description": "Your description"
Please see our docs [here](https://learn.microsoft.com/en-us/connectors/custom-connectors/connector-string-guidance#parameters)

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +    "paths": {
@ecsadm schemes property is required. Please add
 "schemes": ["https"],

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +            "propertyValue": "www.ecoservity.com"
@ecsadm this should be a valid url. please change to "https://www.ecoservity.com"

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +            "propertyValue": "NA"
@ecsadm this should be a valid url.

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +            "propertyValue": "B2B Analytics"
@ecsadm this is not a valid category. you can choose one of the below.
Available categories are: [AI, Business Management, Business Intelligence, Collaboration, Commerce, Communication, Content and Files, Finance, Data, Human Resources, Internet of Things, IT Operations, Lifestyle and Entertainment, Marketing, Productivity, Sales and CRM, Security, Social Media, Website]

2022-10-14 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiProperties.json
> +            "api_key": {
@ecsadm to have a basic authentication type you can just have this connectionParameters as empty property. 
Please change to "connectionParameters": {}

2022-10-14 19:53 UTC, ecsadm commented
> 

@microsoft-github-policy-service agree [company="{Ecoservity}"]

2022-10-18 19:14 UTC, Amjed-Ayoub requested changes

2022-10-18 19:14 UTC, Amjed-Ayoub commented on certified-connectors/USB4SAP/apiDefinition.swagger.json
> +        "definitions": {}
@ecsadm please move the definitions out of the paths scope.

2022-10-18 22:01 UTC, Amjed-Ayoub approved these changes

2022-10-18 22:03 UTC, Amjed-Ayoub commented
Hello @ecsadm,
I hope you are doing well.
Congratulations, your pull request is approved and merged. Please [submit the files to ISV Studio](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) or [update your submission](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-updates) using your latest commit ID, please allow us up to 1-2 weeks to review your submission, and our Engineers will notify you in the “Activity Control” area in ISV Studio. Please [make sure that the icon meets all the requirements](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission#design-an-icon-for-your-connector), that it’s size is 230x230, icon background is not white or transparent and it matches the iconBrandColor property in apiProperties.json file.
After making the submission in ISV Studio, please attach an intro.md file in the activity control section. This file is required and it's different from readme.md. You can [find an example of intro.md file on this page](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) at step 6.
Please [Create an environment in the Preview region](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#create-an-environment-in-the-preview-region). You will use this environment later to [test your connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#test-your-connector) after Microsoft is done with the functional verification for your connector. 
We expect all tests to be completed within 1-2 weeks.
If your connector passes all tests, the deployment process begins, and it typically takes up to 3 to 4 weeks to deploy your connector to all of our regions.
Please let me know if you have any questions or run into any problems while creating or updating your submission.
Thank you very much for working with us.

2022-10-18 22:03 UTC, merged

2022-10-19 03:11 UTC, ecsadm commented
Thanks Amjed, congratulations to you as well.
We will work on this & revert soon with actions.





Thanks a ton,
Anupam Jaiswal
M: ***@***.******@***.***> | T: +1.2145199601
https://www.ecoservity.com/






From: Amjed Ayoub ***@***.***>
Date: Tuesday, October 18, 2022 at 17:03
To: microsoft/PowerPlatformConnectors ***@***.***>
Cc: Anupam Jaiswal ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/PowerPlatformConnectors] USB4SAP : initial pull 10/14/22 (PR #2059)

Hello @ecsadm<https://github.com/ecsadm>,
I hope you are doing well.
Congratulations, your pull request is approved and merged. Please submit the files to ISV Studio<https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio> or update your submission<https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-updates> using your latest commit ID, please allow us up to 1-2 weeks to review your submission, and our Engineers will notify you in the “Activity Control” area in ISV Studio. Please make sure that the icon meets all the requirements<https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission#design-an-icon-for-your-connector>, that it’s size is 230x230, icon background is not white or transparent and it matches the iconBrandColor property in apiProperties.json file.
After making the submission in ISV Studio, please attach an intro.md file in the activity control section. This file is required and it's different from readme.md. You can find an example of intro.md file on this page<https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio> at step 6.
Please Create an environment in the Preview region<https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#create-an-environment-in-the-preview-region>. You will use this environment later to test your connector<https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#test-your-connector> after Microsoft is done with the functional verification for your connector.
We expect all tests to be completed within 1-2 weeks.
If your connector passes all tests, the deployment process begins, and it typically takes up to 3 to 4 weeks to deploy your connector to all of our regions.
Please let me know if you have any questions or run into any problems while creating or updating your submission.
Thank you very much for working with us.

—
Reply to this email directly, view it on GitHub<https://github.com/microsoft/PowerPlatformConnectors/pull/2059#issuecomment-1283056846>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A2Q3FZGZNXDZHQ7QRY2XF3LWD4NCVANCNFSM6AAAAAARFOEDLI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>