Google Books (Independent Publisher)
microsoft/PowerPlatformConnectors pull request #2134
Opened 2022-11-12 07:13 UTC by fordosa90

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [x ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [x ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [x ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2022-11-12 07:14 UTC, fordosa90 commented
![image](https://user-images.githubusercontent.com/36542387/201462285-a2b92688-b145-40b6-b62b-63feacee4645.png)

![image](https://user-images.githubusercontent.com/36542387/201462291-3c3ddfd9-0023-4ac0-ae54-129f35166964.png)

![image](https://user-images.githubusercontent.com/36542387/201462301-b0786889-3b27-44a6-ae2e-05c1b2e13d3f.png)

2022-11-14 17:52 UTC, Amjed-Ayoub commented
Hello @fordosa90,
Thank you very much and congratulations on your new submission. Our Certification Engineers will review it very soon.
Please let us know if you have any questions.
Thank you very much again for working with us.

2022-11-14 20:45 UTC, Amjed-Ayoub requested changes

2022-11-14 20:45 UTC, Amjed-Ayoub commented on independent-publisher-connectors/Google Books/apiDefinition.swagger.json
> +            "email": "fordosa90@gmail.com"
@fordosa90 please provide a "url" property in the contact section.
"url": "Contact URL",

2022-11-15 00:27 UTC, Amjed-Ayoub commented
[[certify-connector]]

2022-11-15 00:28 UTC, Amjed-Ayoub commented
Hello @fordosa90,
I hope you are doing well.
Congratulations, your pull request is approved. We will move forward with the certification process. We are preparing your connector for production deployment and will queue up for the next deployment schedule. Once your connector onboards the next deployment schedule, it starts to deploy your connector in our production environments that typically takes 3-4 weeks. 
Please let us know if you have any questions.
Thank you very much for working with us.

2022-11-15 00:29 UTC, fordosa90 commented
@Amjed-Ayoub thank you for the very quick process, great improvements!
Looking forward for further collaboration!

2022-11-18 22:46 UTC, Amjed-Ayoub commented
Hello @fordosa90 ,
I hope you are doing well.
Your connector is in production deployment and queued up for the next deployment schedule. This process typically takes 3-4 weeks. Please note that the documentation for your connector will not be generated until the deployment process is in the final steps.
Please let us know if you have any questions.
Thank you very much for working with us.

2022-11-23 02:23 UTC, sriyen-msft approved these changes

2022-11-23 02:24 UTC, merged