U.S. Bank Treasury Management (Verified Publisher)
microsoft/PowerPlatformConnectors pull request #2301
Opened 2023-01-13 19:19 UTC by jzworkman

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [x] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [x] I attest that the connector works and I verified by deploying and testing all the operations. 
- [x] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [x] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [x] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [x] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2023-01-13 19:22 UTC, jzworkman commented
@microsoft-github-policy-service agree [company="U.S. Bank"]

2023-01-13 19:23 UTC, jzworkman commented
@microsoft-github-policy-service agree company="U.S. Bank"

2023-01-14 00:13 UTC, Amjed-Ayoub requested changes
@jzworkman thank you so much for working hard on this. I had some small feedback on the PR. but everything is looking great, all operations are good to go.
Thank you so much again.

2023-01-14 00:13 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/apiDefinition.swagger.json
> +    "description": "U.S. Bank payments and treasury banking connector for Microsoft power platform users.",
@jzworkman Is it possible to remove "Microsoft power platform" from the description. it should meet our requirements. please see [here ](https://learn.microsoft.com/en-us/connectors/custom-connectors/connector-string-guidance#connector-info)and [here](https://learn.microsoft.com/en-us/connectors/custom-connectors/certification-submission#write-a-description-for-your-connector).

2023-01-14 00:13 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/apiDefinition.swagger.json
> +      "description": "The avilability of the fields in the below object is dependent on type of transaction.",
@jzworkman all files should be free of grammatical errors and typos. in the description you have "avilability", please change to "availability".

2023-01-14 00:13 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/apiDefinition.swagger.json
> +      "description": "The avilability of the fields in the below object is dependent on type of transaction.",
@jzworkman all files should be free of grammatical errors and typos. in the description you have "avilability", please change to "availability".

2023-01-14 00:13 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/apiDefinition.swagger.json
> +      "description": "The avilability of the fields in the below object is dependent on type of transaction.",
@jzworkman all files should be free of grammatical errors and typos. in the description you have "avilability", please change to "availability".

2023-01-14 00:13 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/apiDefinition.swagger.json
> +      "description": "The avilability of the fields in the below object is dependent on type of transaction.",
@jzworkman all files should be free of grammatical errors and typos. in the description you have "avilability", please change to "availability".

2023-01-14 00:13 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/apiDefinition.swagger.json
> +      "description": "The avilability of the fields in the below object is dependent on type of transaction.",
@jzworkman all files should be free of grammatical errors and typos. in the description you have "avilability", please change to "availability".

2023-01-14 00:13 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/readme.md
> +## U.S. Bank
@jzworkman this great readme file. is it possible to include all required sections from this [template](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/templates/certified-connectors/readme.md). you can see the code [here](https://raw.githubusercontent.com/microsoft/PowerPlatformConnectors/dev/templates/certified-connectors/readme.md).

2023-01-16 13:55 UTC, jzworkman commented
> @jzworkman thank you so much for working hard on this. I had some small feedback on the PR. but everything is looking great, all operations are good to go. Thank you so much again.

Thanks @Amjed-Ayoub Changes have all been made(and caught a few others during my review).  Apologies for the other readme format, the team was told that was just an example file and not a require template.  Have updated the formatting to follow that template now

2023-01-17 20:49 UTC, Amjed-Ayoub requested changes

2023-01-17 20:49 UTC, Amjed-Ayoub commented on certified-connectors/U.S. Bank Treasury Management/apiDefinition.swagger.json
> +    "description": "U.S. Bank payments and treasury banking APIs.",
@jzworkman thank you so much for fixing the connector files. Unfortunately, the word "API" is not allowed in the description too. Please see [here ](https://learn.microsoft.com/en-us/connectors/custom-connectors/connector-string-guidance#connector-info)and [here](https://learn.microsoft.com/en-us/connectors/custom-connectors/certification-submission#write-a-description-for-your-connector). 
Thank you so much again.

2023-01-17 21:21 UTC, Amjed-Ayoub approved these changes

2023-01-17 21:22 UTC, Amjed-Ayoub commented
Hello @jzworkman,
I hope you are doing well.
Congratulations, your pull request is approved and merged. Please [submit the files to ISV Studio](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) or [update your submission](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-updates) using your latest commit ID, please allow us up to 1-2 weeks to review your submission, and our Engineers will notify you in the “Activity Control” area in ISV Studio. Please [make sure that the icon meets all the requirements](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission#design-an-icon-for-your-connector), that it’s size is 230x230, icon background is not white or transparent and it matches the iconBrandColor property in apiProperties.json file.
After making the submission in ISV Studio, please attach an intro.md file in the activity control section. This file is required and it's different from readme.md. You can [find an example of intro.md file on this page](https://docs.microsoft.com/en-us/connectors/custom-connectors/submit-for-certification#submit-to-isv-studio) at step 6.
Please [Create an environment in the Preview region](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#create-an-environment-in-the-preview-region). You will use this environment later to [test your connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-testing#test-your-connector) after Microsoft is done with the functional verification for your connector. 
We expect all tests to be completed within 1-2 weeks.
If your connector passes all tests, the deployment process begins, and it typically takes up to 3 to 4 weeks to deploy your connector to all of our regions.
Please let me know if you have any questions or run into any problems while creating or updating your submission.
Thank you very much for working with us.

2023-01-17 21:22 UTC, merged