Fuzzy Search (Independent Publisher)
microsoft/PowerPlatformConnectors pull request #2520
Opened 2023-04-02 16:36 UTC by happyume

<img width="268" alt="console-test" src="https://user-images.githubusercontent.com/106451522/229366338-5bb0b727-93d7-42f6-86cc-1693c9cbb250.PNG">

<img width="254" alt="pic2" src="https://user-images.githubusercontent.com/106451522/229366343-ddcefa04-fa40-49e2-97f9-85842d2acaf6.PNG">

<img width="246" alt="pic3" src="https://user-images.githubusercontent.com/106451522/229366345-1360774c-c0be-4e55-adc5-eac09d53309e.PNG">

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2023-04-05 20:35 UTC, Amjed-Ayoub requested changes
@happyume you are adding the same file twice. in the root folder and in the independent publisher connectors folder. Please remove the files from the root of this repo.
![image](https://user-images.githubusercontent.com/97551789/230205388-6e3e1bbd-1b73-486f-b65d-9da4975cbcca.png)

2023-04-05 20:35 UTC, Amjed-Ayoub commented on independent-publisher-connectors/Fuzzy Search/apiDefinition.swagger.json
> +      "propertyValue":"https://sa018.azurewebsites.net"
@happyume this should be a valid URL to the product.

2023-04-05 20:35 UTC, Amjed-Ayoub commented on independent-publisher-connectors/Fuzzy Search/apiDefinition.swagger.json
> +      "propertyValue":"https://sa018.azurewebsites.net"
@happyume please replace with a valid URL to the privacy policy page.

2023-04-05 20:35 UTC, Amjed-Ayoub commented on independent-publisher-connectors/Fuzzy Search/readme.md
> +## Fuzzy Search
@happyume please include all required section in the readme file. please follow our template [here ](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/templates/Independent%20Publisher/readme.md)and for raw code view [here](https://raw.githubusercontent.com/microsoft/PowerPlatformConnectors/dev/templates/Independent%20Publisher/readme.md).

2023-04-05 20:35 UTC, Amjed-Ayoub commented on independent-publisher-connectors/Fuzzy Search/apiProperties.json
> +     "stackOwner": "Mitanshu Garg"
@happyume stackOnwer should be the API Owner. 
"stackOwner": "Name of company or organization that connector is connecting to."

2023-05-10 19:54 UTC, Amjed-Ayoub commented
Hello @happyume ,
I hope you are doing well.
I am following up with you to see how things are going with preparing your connector.
Please let us know if you have any questions.
Thank you.

2023-05-13 00:43 UTC, happyume commented
Hi
Thanks for the follow-up.

I am on holiday till end of May. I do have a few questions and will get
back to you after the holidays when I have access to my laptop and account.

Do you think it will be possible to keep my pull request open till that
time?

Regards
Mitanshu

On Thu, May 11, 2023, 1:24 AM Amjed Ayoub ***@***.***> wrote:

> Hello @happyume <https://github.com/happyume> ,
> I hope you are doing well.
> I am following up with you to see how things are going with preparing your
> connector.
> Please let us know if you have any questions.
> Thank you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/PowerPlatformConnectors/pull/2520#issuecomment-1542725701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZMFEQQCFMJGWJ6LLZ7AHRDXFPW63ANCNFSM6AAAAAAWQMZJTE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-06 10:49 UTC, vmanoharas commented
Hello @happyume 
I hope you are doing well.
I am following up with you to see how things are going with preparing your connector.
Please let us know if you have any questions.
Thank you.

2024-05-21 12:10 UTC, vmanoharas commented
Hello @happyume, 

This PR is in open state from many months. I am closing this PR, kindly reopen/create new PR, if you have any progress.

2024-05-21 12:10 UTC, closed without merging