Fixing DT file path issue
microsoft/PowerPlatformConnectors pull request #2592
Opened 2023-04-21 00:26 UTC by HamshavathiM

Fixing DT file path issue

2023-04-21 00:45 UTC, Amjed-Ayoub requested changes
@HamshavathiM please add a readme file. Thanks

2023-04-21 00:47 UTC, HamshavathiM commented
> @HamshavathiM please add a readme file. Thanks

The Readme file already exists : https://github.com/microsoft/PowerPlatformConnectors/blob/dev/certified-connectors/TranslatorV3/Readme.md

2023-04-21 16:45 UTC, HamshavathiM commented
> @HamshavathiM please add a readme file. Thanks

2023-04-22 06:45 UTC, Amjed-Ayoub approved these changes

2023-04-22 06:45 UTC, merged