Add files via upload
microsoft/PowerPlatformConnectors pull request #2747
Opened 2023-06-23 06:58 UTC by jrsinnovation

---
### When submitting a connector, please make sure that you follow the requirements below, otherwise your PR might be rejected. We want to make you have a well-built connector, a smooth certification experience, and your users are happy :) 

If this is your first time submitting to GitHub and you need some help, please sign up for this [session](https://forms.office.com/pages/responsepage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMTFJWFFGVUxBNUFZQjZWRUdaOE5BMFkwNS4u). 

- [ ] I attest that the connector doesn't exist on the Power Platform today. I've verified by checking the pull requests in GitHub and by searching for the connector on the platform or in the documentation. 
- [ ] I attest that the connector works and I verified by deploying and testing all the operations. 
- [ ] I attest that I have added detailed descriptions for all operations and parameters in the swagger file.
- [ ] I attest that I have added response schemas to my actions, unless the response schema is dynamic. 
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a connector icon.

If you are an Independent Publisher, you must also attest to the following to ensure a smooth publishing process:
- [ ] I have named this PR after the pattern of "Connector Name (Independent Publisher)" ex: HubSpot Marketing (Independent Publisher)
- [ ] Within this PR markdown file, I have pasted screenshots that show: 3 unique operations (actions/triggers) working within a Flow. This can be in one flow or part of multiple flows. For each one of those flows, I have pasted in screenshots of the Flow succeeding. 
- [ ] Within this PR markdown file, I have pasted in a screenshot from the Test operations section within the Custom Connector UI.
- [ ] If the connector uses OAuth, I have provided detailed steps on how to create an app in the readme.md.

2023-06-23 07:42 UTC, jrsinnovation commented
Please validate the connector

2023-06-26 20:52 UTC, Amjed-Ayoub requested changes
@jrsinnovation Please rename the connector folder from "shared_hvi-20ins-20specific-20vehicle-5fbc7b7a898d7451-02a9ed7ac5553fca" to the connector name/title "Inspection per vehicle" and would recommend you change the title to "HVI Inspection per vehicle".

Please add a readme file to the pull request. Please include all required sections in the readme file. please see out template [here ](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/templates/certified-connectors/readme.md)and for raw code view [here](https://[raw.githubusercontent.com/microsoft/PowerPlatformConnectors/dev/templates/certified-connectors/readme.md%5D(https://raw.githubusercontent.com/microsoft/PowerPlatformConnectors/dev/templates/certified-connectors/readme.md)).

2023-06-26 20:52 UTC, Amjed-Ayoub commented on certified-connectors/shared_hvi-20ins-20specific-20vehicle-5fbc7b7a898d7451-02a9ed7ac5553fca/settings.json
> +{
@jrsinnovation Please remove the icon.png and settings.json files as they are not required in GitHub.

2023-07-05 12:21 UTC, jrsinnovation commented on certified-connectors/shared_hvi-20ins-20specific-20vehicle-5fbc7b7a898d7451-02a9ed7ac5553fca/settings.json
> +{
I have deleted those 2 files icon.png and settings.json.

2023-07-05 12:28 UTC, jrsinnovation commented
@microsoft-github-policy-service agree company="JRS Innovation"

2023-07-05 12:55 UTC, jrsinnovation commented
please review it I have made the changes that you have asked to

2023-07-14 13:20 UTC, jrsinnovation commented
Hy Amjed,

please review it i have added a new folder with name HVI Inspection per Vehicle

2023-07-19 11:58 UTC, jrsinnovation commented
@Amjed-Ayoub  Please verify it

2023-07-19 12:02 UTC, jrsinnovation reviewed
@Amjed-Ayoub  review it

2023-07-19 14:18 UTC, jrsinnovation commented
Hi, could you please provide an update. I have to report back the reason for delay in publishing the connector. Let me know if a meeting/ teams meeting can speedup this process?

2023-07-22 12:48 UTC, jrsinnovation commented
![image](https://github.com/microsoft/PowerPlatformConnectors/assets/130588212/5aeb133f-d8f1-449b-80ba-9bdd32d142f0)

@Amjed-Ayoub you can check i have validated the swagger file then also it is showing failing in git.
Please review it and reply back.

2023-07-29 10:23 UTC, jrsinnovation commented
@Amjed-Ayoub  can you please let me know why the validation is failing in git as i have validated it through paconn validate command and there it was successfully validated. Please Check and let me know

paconn validate Image Link:-
https://user-images.githubusercontent.com/130588212/255330457-5aeb133f-d8f1-449b-80ba-9bdd32d142f0.png

2023-07-31 13:09 UTC, closed without merging