Submit for certification
microsoft/PowerPlatformConnectors pull request #526
Opened 2020-10-26 02:11 UTC by lulut

---
Please check the following conditions for your PR.

- [x] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [x] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

2020-10-26 22:18 UTC, dougelliott requested changes

2020-10-26 22:18 UTC, dougelliott commented on certified-connectors/Yeeflow/apiProperties.json
> +          "clientId": "18e3f376-5cfd-1ed1-770f-ba933a6041d1",
The clientId should be replaced with a dummy value, or `null` for the purposes of open sourcing. You will be able to provide it when submitting the connector for certification.

2020-10-28 01:15 UTC, dougelliott submitted a review, later dismissed

2020-10-28 02:00 UTC, sriyen-msft requested changes

2020-10-28 02:00 UTC, sriyen-msft commented on certified-connectors/Yeeflow/apiProperties.json
> +          "clientId": "00000000-0000-0000-0000-000000000000",
@lulut You can provide the value for `clientId` as "[DUMMY_VALUE]" instead it.

2020-10-29 01:34 UTC, dougelliott approved these changes

2020-10-29 01:48 UTC, sriyen-msft approved these changes

2020-10-29 01:48 UTC, merged