Patch 1
microsoft/PowerPlatformConnectors pull request #551
Opened 2020-11-10 08:01 UTC by AravindanYnoox

---
Please check the following conditions for your PR.

- [ ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

2020-11-10 22:08 UTC, dougelliott requested changes
The `settings.json` and `icon.png` files do not need to be open sourced as part of our requirement, so they can be removed.

That said, we do require that a `readme.md` be included in open sourcing. To give you an idea of what we're looking for, please refer to the [Azure Key Vault](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/custom-connectors/AzureKeyVault/Readme.md) example.

2020-11-11 00:06 UTC, sriyen-msft approved these changes

2020-11-11 05:12 UTC, AravindanYnoox commented
Updated with review comments. Please verify and complete the request.

2020-11-12 00:05 UTC, dougelliott approved these changes

2020-11-12 01:24 UTC, sriyen-msft approved these changes

2020-11-12 01:24 UTC, merged