Egoi connector
microsoft/PowerPlatformConnectors pull request #625
Opened 2020-12-23 12:55 UTC by fbobiano

New E-goi connector

2020-12-23 22:01 UTC, dougelliott requested changes

2020-12-23 22:01 UTC, dougelliott commented on certified-connectors/E-goi/apiProperties.json
> +    "iconBrandColor": "#FFFFFF",
Unfortunately, pure white (#FFFFFF) isn't an allowed color for the icon. It can be off-white if you would like.

2020-12-23 22:01 UTC, dougelliott commented on certified-connectors/E-goi/apiDefinition.swagger.json
> +    "description": "Consume E-goi API for add/update contacts, attach tags and send transactional SMS.",
Could the description be expanded to briefly discuss the E-goi service as well?

2020-12-24 01:35 UTC, sriyen-msft submitted a review, later dismissed

2021-01-06 05:28 UTC, dougelliott approved these changes

2021-01-06 05:28 UTC, merged