Add Datelist connector
microsoft/PowerPlatformConnectors pull request #754
Opened 2021-04-04 06:49 UTC by aclarembeau

# Datelist - Microsoft Flow Connector
Microsoft flow connector for https://datelist.io 
Datelist is an online booking system platform that allows customers taking meetings online. 

## Triggers

- New booking: Triggers when someone books a meeting in the Datelist platform 

## Actions

- Get calendars: List all available calendars in Datelist.io 

# Questions 
I've tried to make our organization name as the Stack owner (datelist.io), but I get the following error: 
> The request content was invalid and could not be deserialized: 'Could not find member 'stackOwner' on object of type 'ApiPropertiesDefinition'. Path 'properties.stackOwner', line 1, position 384.'. 

So, I've put my personal name here "Clarembeau Alexis", do you know what are the accepted values in that field? 

# Checks done
Please check the following conditions for your PR.

- [X] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [X] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

2021-04-06 00:17 UTC, sriyen-msft approved these changes

2021-04-06 00:18 UTC, sriyen-msft commented on custom-connectors/Datelist/apiProperties.json
> +    "publisher": "Alexis Clarembeau"
@aclarembeau Please add `stackOwner` property as well

2021-04-09 01:25 UTC, dougelliott requested changes

2021-04-09 01:25 UTC, dougelliott commented on custom-connectors/Datelist/apiProperties.json
> +    "publisher": "Alexis Clarembeau"
We'd recommend that the `publisher` and `stackOwner` properties do not contain PII. It's better for it to be representative of the company as a whole.

2021-04-09 01:26 UTC, dougelliott commented
@aclarembeau Could you please also sign the CLA? Thanks!

2021-04-10 13:16 UTC, aclarembeau commented
Hello, and thank you for the feedbacks. 
I've signed the CLA, removed PII and used ACL Software (our company) as a publisher and a stackowner. 
Is that good with those modifications?

2021-04-20 23:23 UTC, sriyen-msft requested changes

2021-04-20 23:23 UTC, sriyen-msft commented on custom-connectors/Datelist/apiDefinition.swagger.json
> +      "Cl\u00e9 API": []
@aclarembeau Unicodes are not allowed in any connector's artifact, Can you please remove them all.

2021-04-26 23:23 UTC, sriyen-msft requested changes

2021-04-26 23:23 UTC, sriyen-msft commented on custom-connectors/Datelist/README.md
> +Microsoft flow connector for https://datelist.io
@aclarembeau `Flow` is an outdated word in the product, Can you please update is with `Power Automate`

2021-04-26 23:23 UTC, sriyen-msft commented on custom-connectors/Datelist/apiDefinition.swagger.json
> +      "Cl\u00e9 API": []
@aclarembeau Any update ?

2021-04-30 01:55 UTC, sriyen-msft commented
@aclarembeau I'm just checking in to see how things are going with updating your connector as per the feedback. Feel free to reach out with any questions you may have.

2021-04-30 04:35 UTC, aclarembeau commented
Hello @sriyen-msft , sorry for the delay. I've applied your recommendations; so, it's good on my side.

2021-04-30 22:07 UTC, sriyen-msft approved these changes

2021-04-30 22:08 UTC, merged