Added batch trigger functionality
microsoft/PowerPlatformConnectors pull request #760
Opened 2021-04-09 07:38 UTC by Joerio

---
Please check the following conditions for your PR.

- [ ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

2021-04-09 16:42 UTC, mamurshe requested changes

2021-04-09 16:42 UTC, mamurshe commented on certified-connectors/Connect2All/apiProperties.json
> +    "stackOwner":  "GAC Business Solutions"
Please remove the extra space.

2021-04-14 06:59 UTC, Joerio commented on certified-connectors/Connect2All/apiProperties.json
> +    "stackOwner":  "GAC Business Solutions"
Space is removed in latest commit

2021-04-20 23:19 UTC, sriyen-msft approved these changes

2021-04-26 23:17 UTC, sriyen-msft approved these changes

2021-04-26 23:17 UTC, sriyen-msft approved these changes

2021-05-04 21:04 UTC, ptalrejagithub commented
@mamurshe, can you please review the changes.

2021-05-19 05:49 UTC, mamurshe approved these changes

2021-05-20 20:09 UTC, merged