version 2
microsoft/PowerPlatformConnectors pull request #837
Opened 2021-05-21 16:42 UTC by gsmcmurtrie

Changes include:
Removing "Get Historical Data" action as this was exposing a Web API end-point marked as obsolete.

Correcting a number of the defined response schemas that had content nested under a "datasource" element.

Updating action descriptions and markdown readme.

Adding required meta data to swagger API definition.

---
Please check the following conditions for your PR.

- [ ] `apiDefinition.swagger.json` is validated using `paconn validate` command.
- [ ] `apiProperties.json` has a valid brand color. Invalid brand colors are `#007ee5` and `#ffffff`.

2021-05-21 19:11 UTC, sriyen-msft commented
@gsmcmurtrie Please sign the CLA

2021-05-21 19:16 UTC, sriyen-msft requested changes

2021-05-21 19:16 UTC, sriyen-msft commented on certified-connectors/Industrial App Store/apiDefinition.swagger.json
> +                      "description": "UtcSampleTime"
@gsmcmurtrie Can you please provide valid description values.

Documentation - [Summary and Description values](https://docs.microsoft.com/connectors/custom-connectors/certification-submission#operation-and-parameter-summaries-and-descriptions)

Applies to all the description values in the swagger

2021-05-21 19:16 UTC, sriyen-msft commented on certified-connectors/Industrial App Store/apiProperties.json
> +          "clientId": "18e880e61fe84e9485fda4eb41462554",
@gsmcmurtrie You can replace the clientId value with `[[Dummy]]`

2021-05-21 19:16 UTC, sriyen-msft commented on certified-connectors/Industrial App Store/apiProperties.json
> +    "iconBrandColor": "#ffffff",
@gsmcmurtrie Please note that white background color for icon is not allowed.

Documentation - [Icon](https://docs.microsoft.com/connectors/custom-connectors/certification-submission#icon)

2021-05-21 22:23 UTC, ptalrejagithub commented
@gsmcmurtrie You have submitted the intro.md instead of readme.md in open repo. There is a difference between intro.md and readme.md files, the intro.md file is required for certification and its content would be published and displayed in your connector's documentation page. Readme.md file is only required for open sourcing your connector which can be helpful to the open source users who may want to contribute in your connector. Here is an [example](https://github.com/st0014/PowerPlatformConnectors/blob/dev/custom-connectors/AzureKeyVault/Readme.md)

2021-05-28 23:56 UTC, sriyen-msft approved these changes

2021-05-28 23:56 UTC, merged