Uk government bank holidays ipc
microsoft/PowerPlatformConnectors pull request #906
Opened 2021-06-20 17:48 UTC by martynlesbirel

---
When submitting a connector, please check the following conditions for your PR.

- [ ] I attest that the connector works and I verified by deploying and testing all the operations.
- [ ] I validated the swagger file, `apiDefinition.swagger.json`, by running `paconn validate` command.
- [ ] If this is a certified connector, I confirm that `apiProperties.json` has a valid brand color and doesn't use an invalid brand color, `#007ee5` or `#ffffff`. If this is an independent publisher connector, I confirm that I am not submitting a logo.

2021-06-22 23:51 UTC, sriyen-msft requested changes

2021-06-22 23:51 UTC, sriyen-msft commented on independent-publisher-connectors/U.K. Government Bank Holidays/UK-Bank-Holidays.swagger.json
> +      "email": "ipc-author-bh@outlook.com"
@martynlesbirel Please add `url` property as well

2021-06-25 03:29 UTC, sriyen-msft commented on independent-publisher-connectors/U.K. Government Bank Holidays/UK-Bank-Holidays.swagger.json
> +      "email": "ipc-author-bh@outlook.com"
@martynlesbirel Please add url property as well

Please let us know if you do not have one.

2021-06-25 03:31 UTC, sriyen-msft commented
[[certify-connector]]

2021-06-29 00:10 UTC, sriyen-msft commented
[[certify-connector]]

2021-06-29 01:05 UTC, sriyen-msft requested changes

2021-06-29 01:05 UTC, sriyen-msft commented on independent-publisher-connectors/U.K. Government Bank Holidays/apiProperties.json
> +    "website": "https://www.gov.uk/bank-holidays",
@martynlesbirel Can you please remove website property.

2021-07-06 16:31 UTC, mamurshe approved these changes

2021-07-19 18:06 UTC, merged